// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/DataForge/LexerCup.flex

package DataForge;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\2\2\1\1\22\0\1\1\1\0\1\3"+
    "\5\0\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\12\14\1\15\1\16\1\17\1\20\2\0\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\27\1\34\1\35\1\36\1\37\1\40"+
    "\1\27\1\41\1\42\1\43\1\44\1\45\1\27\1\46"+
    "\1\47\1\50\1\51\1\0\1\52\1\0\1\27\1\0"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\27\1\34\1\35\1\36\1\37\1\40"+
    "\1\27\1\41\1\42\1\43\1\44\1\45\1\27\1\46"+
    "\1\47\1\50\12\0\1\2\252\0\2\53\115\0\1\54"+
    "\u01a8\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\1"+
    "\1\16\1\17\16\20\1\21\1\22\1\1\1\0\1\23"+
    "\1\0\1\24\1\25\5\20\1\0\5\20\1\0\6\20"+
    "\1\0\4\20\1\0\1\20\1\0\1\26\1\27\3\20"+
    "\1\30\1\20\1\30\1\20\1\31\3\20\1\0\1\20"+
    "\1\32\1\20\1\33\1\34\1\35\1\33\2\20\1\0"+
    "\2\36\1\37\1\20\1\0\1\20\1\40\1\37\1\41"+
    "\2\20\1\0\1\20\1\42\1\43\1\44\2\20\1\0"+
    "\2\20\1\0\1\45\2\20\1\0\1\20\1\0\2\20"+
    "\1\0\2\20\1\0\3\20\1\0\1\46\2\47\1\50"+
    "\1\20\1\50\1\20\1\0\2\20\1\0\1\51\1\20"+
    "\1\0\1\52\4\20\1\0\1\20\1\0\1\20\2\53"+
    "\2\54\1\20\1\0\2\55\2\20\1\0\1\20\1\0"+
    "\1\20\1\0\2\56\1\57\1\60\1\61\1\60\1\61"+
    "\1\20\1\0\1\62\1\20\1\0\2\63\1\20\1\0"+
    "\2\64\2\65\2\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[188];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\55\0\55\0\55\0\55"+
    "\0\55\0\55\0\55\0\55\0\264\0\341\0\55\0\u010e"+
    "\0\55\0\55\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c"+
    "\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384"+
    "\0\55\0\55\0\u03b1\0\207\0\55\0\u03de\0\55\0\55"+
    "\0\u040b\0\u0438\0\u0465\0\u0492\0\u04bf\0\u04ec\0\u0519\0\u0546"+
    "\0\u0573\0\u05a0\0\u05cd\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae"+
    "\0\u06db\0\u0708\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9\0\u0816"+
    "\0\u0843\0\u0870\0\u03de\0\u0168\0\u089d\0\u08ca\0\u08f7\0\u0168"+
    "\0\u0924\0\55\0\u0951\0\u0168\0\u097e\0\u09ab\0\u09d8\0\u0a05"+
    "\0\u0a32\0\u0168\0\u0a5f\0\u0168\0\u0a8c\0\u0168\0\55\0\u0ab9"+
    "\0\u0ae6\0\u0b13\0\u0168\0\55\0\u0168\0\u0b40\0\u0b6d\0\u0b9a"+
    "\0\u0bc7\0\55\0\u0168\0\u0bf4\0\u0c21\0\u0c4e\0\u0c7b\0\u0168"+
    "\0\u0168\0\u0168\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89"+
    "\0\u0168\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4"+
    "\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff\0\u102c"+
    "\0\u0168\0\u1059\0\u1086\0\u0168\0\u10b3\0\55\0\u10e0\0\u110d"+
    "\0\u113a\0\u1167\0\u1194\0\u0168\0\u11c1\0\u11ee\0\u0168\0\u121b"+
    "\0\u1248\0\u1275\0\u12a2\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u1383"+
    "\0\u13b0\0\u0168\0\55\0\u13dd\0\u140a\0\u0168\0\55\0\u1437"+
    "\0\u1464\0\u1491\0\u14be\0\u14eb\0\u1518\0\u1545\0\u0168\0\55"+
    "\0\u0168\0\u0168\0\u0168\0\55\0\55\0\u1572\0\u159f\0\u0168"+
    "\0\u15cc\0\u15f9\0\u0168\0\55\0\u1626\0\u1653\0\u0168\0\55"+
    "\0\u0168\0\55\0\u0168\0\55";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[188];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\24"+
    "\1\30\1\31\2\24\1\32\1\33\2\24\1\34\1\35"+
    "\1\36\1\37\1\24\1\40\3\24\1\41\1\42\1\2"+
    "\1\43\56\0\1\3\53\0\3\44\1\45\51\44\12\0"+
    "\1\46\1\0\1\15\55\0\1\47\50\0\1\50\57\0"+
    "\1\24\5\0\17\24\1\51\7\24\20\0\1\24\5\0"+
    "\27\24\20\0\1\24\5\0\7\24\1\52\5\24\1\53"+
    "\11\24\20\0\1\24\5\0\10\24\1\54\4\24\1\55"+
    "\11\24\2\0\1\56\15\0\1\24\5\0\11\24\1\57"+
    "\2\24\1\60\7\24\1\61\2\24\20\0\1\24\5\0"+
    "\17\24\1\62\7\24\20\0\1\24\5\0\10\24\1\63"+
    "\16\24\2\0\1\64\15\0\1\24\5\0\1\65\26\24"+
    "\20\0\1\24\5\0\1\66\3\24\1\67\3\24\1\70"+
    "\4\24\1\71\4\24\1\72\4\24\2\0\1\73\15\0"+
    "\1\24\5\0\17\24\1\74\7\24\20\0\1\24\5\0"+
    "\4\24\1\75\22\24\20\0\1\24\5\0\22\24\1\76"+
    "\4\24\20\0\1\24\5\0\10\24\1\77\16\24\2\0"+
    "\1\100\15\0\1\24\5\0\1\101\26\24\50\0\1\102"+
    "\24\0\1\103\54\0\1\24\5\0\17\24\1\104\7\24"+
    "\20\0\1\24\5\0\1\105\26\24\20\0\1\24\5\0"+
    "\12\24\1\106\1\24\1\107\12\24\20\0\1\24\5\0"+
    "\23\24\1\110\3\24\20\0\1\24\5\0\22\24\1\111"+
    "\4\24\51\0\1\112\23\0\1\24\5\0\4\24\1\113"+
    "\22\24\20\0\1\24\5\0\3\24\1\114\23\24\20\0"+
    "\1\24\5\0\4\24\1\115\22\24\20\0\1\24\5\0"+
    "\1\116\26\24\20\0\1\24\5\0\20\24\1\117\6\24"+
    "\3\0\1\120\42\0\1\120\11\0\1\120\14\0\1\24"+
    "\5\0\1\24\1\121\25\24\20\0\1\24\5\0\24\24"+
    "\1\122\2\24\20\0\1\24\5\0\3\24\1\123\23\24"+
    "\20\0\1\24\5\0\14\24\1\124\12\24\20\0\1\24"+
    "\5\0\3\24\1\125\23\24\20\0\1\24\5\0\12\24"+
    "\1\126\14\24\42\0\1\127\32\0\1\24\5\0\10\24"+
    "\1\130\4\24\1\131\11\24\2\0\1\132\15\0\1\24"+
    "\5\0\20\24\1\133\6\24\3\0\1\134\14\0\1\24"+
    "\5\0\13\24\1\135\13\24\20\0\1\24\5\0\21\24"+
    "\1\136\5\24\47\0\1\137\25\0\1\24\5\0\12\24"+
    "\1\140\4\24\1\141\7\24\41\0\1\142\33\0\1\24"+
    "\5\0\17\24\1\143\7\24\20\0\1\24\5\0\22\24"+
    "\1\144\4\24\20\0\1\24\5\0\20\24\1\145\6\24"+
    "\3\0\1\146\14\0\1\24\5\0\1\24\1\147\25\24"+
    "\20\0\1\24\5\0\24\24\1\150\1\151\1\24\20\0"+
    "\1\24\5\0\2\24\1\152\24\24\20\0\1\24\5\0"+
    "\16\24\1\153\10\24\20\0\1\24\5\0\21\24\1\154"+
    "\5\24\47\0\1\155\25\0\1\24\5\0\4\24\1\156"+
    "\22\24\20\0\1\24\5\0\10\24\1\157\16\24\2\0"+
    "\1\160\15\0\1\24\5\0\1\161\26\24\20\0\1\24"+
    "\5\0\14\24\1\162\12\24\20\0\1\24\5\0\6\24"+
    "\1\163\20\24\42\0\1\164\32\0\1\24\5\0\22\24"+
    "\1\165\4\24\50\0\1\166\24\0\1\24\5\0\22\24"+
    "\1\167\4\24\20\0\1\24\5\0\10\24\1\170\16\24"+
    "\2\0\1\171\15\0\1\24\5\0\13\24\1\172\13\24"+
    "\20\0\1\24\5\0\15\24\1\173\11\24\43\0\1\174"+
    "\31\0\1\24\5\0\12\24\1\175\14\24\20\0\1\24"+
    "\5\0\7\24\1\176\17\24\20\0\1\24\5\0\15\24"+
    "\1\177\11\24\43\0\1\200\31\0\1\24\5\0\12\24"+
    "\1\201\14\24\20\0\1\24\5\0\1\202\26\24\26\0"+
    "\1\203\46\0\1\24\5\0\21\24\1\204\5\24\20\0"+
    "\1\24\5\0\17\24\1\205\7\24\47\0\1\206\25\0"+
    "\1\24\5\0\12\24\1\207\14\24\40\0\1\210\34\0"+
    "\1\24\5\0\4\24\1\211\22\24\20\0\1\24\5\0"+
    "\1\212\26\24\26\0\1\213\46\0\1\24\5\0\14\24"+
    "\1\214\12\24\20\0\1\24\5\0\12\24\1\215\14\24"+
    "\40\0\1\216\34\0\1\24\5\0\4\24\1\217\22\24"+
    "\20\0\1\24\5\0\1\24\1\220\10\24\1\221\3\24"+
    "\1\222\10\24\20\0\1\24\5\0\6\24\1\223\20\24"+
    "\34\0\1\224\40\0\1\24\5\0\14\24\1\225\12\24"+
    "\42\0\1\226\32\0\1\24\5\0\1\227\26\24\20\0"+
    "\1\24\5\0\15\24\1\230\11\24\43\0\1\231\31\0"+
    "\1\24\5\0\20\24\1\232\6\24\3\0\1\233\14\0"+
    "\1\24\5\0\14\24\1\234\12\24\42\0\1\235\32\0"+
    "\1\24\5\0\4\24\1\236\22\24\32\0\1\237\42\0"+
    "\1\24\5\0\1\240\26\24\20\0\1\24\5\0\10\24"+
    "\1\241\16\24\2\0\1\242\15\0\1\24\5\0\10\24"+
    "\1\243\16\24\2\0\1\244\15\0\1\24\5\0\17\24"+
    "\1\245\7\24\45\0\1\246\27\0\1\24\5\0\1\247"+
    "\26\24\26\0\1\250\46\0\1\24\5\0\13\24\1\251"+
    "\13\24\20\0\1\24\5\0\24\24\1\252\1\253\1\24"+
    "\52\0\1\254\1\255\21\0\1\24\5\0\26\24\1\256"+
    "\54\0\1\257\20\0\1\24\5\0\17\24\1\260\7\24"+
    "\20\0\1\24\5\0\14\24\1\261\12\24\42\0\1\262"+
    "\32\0\1\24\5\0\4\24\1\263\22\24\32\0\1\264"+
    "\42\0\1\24\5\0\1\265\26\24\26\0\1\266\46\0"+
    "\1\24\5\0\1\267\26\24\26\0\1\270\46\0\1\24"+
    "\5\0\4\24\1\271\22\24\32\0\1\272\42\0\1\24"+
    "\5\0\13\24\1\273\13\24\41\0\1\274\17\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5760];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\10\11\2\1\1\11\1\1\2\11"+
    "\16\1\2\11\1\1\1\0\1\11\1\0\2\11\5\1"+
    "\1\0\5\1\1\0\6\1\1\0\4\1\1\0\1\1"+
    "\1\0\7\1\1\11\5\1\1\0\6\1\1\11\2\1"+
    "\1\0\1\1\1\11\2\1\1\0\2\1\1\11\3\1"+
    "\1\0\6\1\1\0\2\1\1\0\3\1\1\0\1\1"+
    "\1\0\2\1\1\0\2\1\1\0\3\1\1\0\5\1"+
    "\1\11\1\1\1\0\2\1\1\0\2\1\1\0\5\1"+
    "\1\0\1\1\1\0\4\1\1\11\1\1\1\0\1\1"+
    "\1\11\2\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\11\3\1\2\11\1\1\1\0\2\1\1\0\1\1"+
    "\1\11\1\1\1\0\1\1\1\11\1\1\1\11\1\1"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[188];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCup(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(sym.ERROR, yycolumn, yyline, yytext());
            }
          // fall through
          case 55: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 56: break;
          case 3:
            { System.out.println("--<Parentesis_Izq: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Parentesis_Izq, yycolumn, yyline, yytext());
            }
          // fall through
          case 57: break;
          case 4:
            { System.out.println("--<Parentesis_Der: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Parentesis_Der, yycolumn, yyline, yytext());
            }
          // fall through
          case 58: break;
          case 5:
            { System.out.println("--<Signo_Multiplicacion: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Multiplicacion, yycolumn, yyline, yytext());
            }
          // fall through
          case 59: break;
          case 6:
            { System.out.println("--<Signo_Suma: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Suma, yycolumn, yyline, yytext());
            }
          // fall through
          case 60: break;
          case 7:
            { System.out.println("--<Coma: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Coma, yycolumn, yyline, yytext());
            }
          // fall through
          case 61: break;
          case 8:
            { System.out.println("--<Signo_Resta: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Resta, yycolumn, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 9:
            { System.out.println("--<Punto: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Punto, yycolumn, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 10:
            { System.out.println("--<Signo_Division: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Division, yycolumn, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 11:
            { System.out.println("--<Numero: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Numero, yycolumn, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 12:
            { System.out.println("--<Dos_Puntos: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Dos_Puntos, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 13:
            { System.out.println("--<Punto_Coma: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Punto_Coma, yycolumn, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 14:
            { System.out.println("--<Signo_Igual: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Igual, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 15:
            { System.out.println("--<Signo_Arroba: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Arroba, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 16:
            { System.out.println("--<Identificador: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Identificador, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 17:
            { System.out.println("--<Corchete_Izq: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Corchete_Izq, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 18:
            { System.out.println("--<Corchete_Der: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Corchete_Der, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 19:
            { System.out.println("--<CHAR_GENERAL: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.char_general, yycolumn, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 20:
            { System.out.println("--<DosPuntos_Dobles: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.DosPuntos_Dobles, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 21:
            { System.out.println("--<Signo_Indicador: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Indicador, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 22:
            { System.out.println("--<Decimal: " + yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">"); return new Symbol(sym.Decimal, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 23:
            { System.out.println("--<Array: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Array, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 24:
            { System.out.println("--<Fun_Division: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Division, yycolumn, yyline, yytext());
            }
          // fall through
          case 78: break;
          case 25:
            { System.out.println("--<End: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.End, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 26:
            { System.out.println("--<Fun_Maximo: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Maximo, yycolumn, yyline, yytext());
            }
          // fall through
          case 80: break;
          case 27:
            { System.out.println("--<Fun_Minimo: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Minimo, yycolumn, yyline, yytext());
            }
          // fall through
          case 81: break;
          case 28:
            { System.out.println("--<Fun_Mod: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Mod, yycolumn, yyline, yytext());
            }
          // fall through
          case 82: break;
          case 29:
            { System.out.println("--<Fun_Multiplicacion: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Multiplicacion, yycolumn, yyline, yytext());
            }
          // fall through
          case 83: break;
          case 30:
            { System.out.println("--<Fun_Resta: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Resta, yycolumn, yyline, yytext());
            }
          // fall through
          case 84: break;
          case 31:
            { System.out.println("--<Fun_Suma: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Suma, yycolumn, yyline, yytext());
            }
          // fall through
          case 85: break;
          case 32:
            { System.out.println("--<Variable: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Variable, yycolumn, yyline, yytext());
            }
          // fall through
          case 86: break;
          case 33:
            { System.out.println("--<Fun_Char: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Char, yycolumn, yyline, yytext());
            }
          // fall through
          case 87: break;
          case 34:
            { System.out.println("--<Eje_X: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Eje_X, yycolumn, yyline, yytext());
            }
          // fall through
          case 88: break;
          case 35:
            { System.out.println("--<Eje_Y: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Eje_Y, yycolumn, yyline, yytext());
            }
          // fall through
          case 89: break;
          case 36:
            { System.out.println("--<Ejecutar: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Ejecutar, yycolumn, yyline, yytext());
            }
          // fall through
          case 90: break;
          case 37:
            { System.out.println("--<Fun_Moda: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Moda, yycolumn, yyline, yytext());
            }
          // fall through
          case 91: break;
          case 38:
            { System.out.println("--<Grafica_Label: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Label, yycolumn, yyline, yytext());
            }
          // fall through
          case 92: break;
          case 39:
            { System.out.println("--<Fun_Media: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Media, yycolumn, yyline, yytext());
            }
          // fall through
          case 93: break;
          case 40:
            { System.out.println("--<Imprimir: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Imprimir, yycolumn, yyline, yytext());
            }
          // fall through
          case 94: break;
          case 41:
            { System.out.println("--<Columna: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Columna, yycolumn, yyline, yytext());
            }
          // fall through
          case 95: break;
          case 42:
            { System.out.println("--<Fun_Double: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Double, yycolumn, yyline, yytext());
            }
          // fall through
          case 96: break;
          case 43:
            { System.out.println("--<Grafica_Titulo: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Titulo, yycolumn, yyline, yytext());
            }
          // fall through
          case 97: break;
          case 44:
            { System.out.println("--<Grafica_Valores: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Valores, yycolumn, yyline, yytext());
            }
          // fall through
          case 98: break;
          case 45:
            { System.out.println("--<Fun_Consola: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Consola, yycolumn, yyline, yytext());
            }
          // fall through
          case 99: break;
          case 46:
            { System.out.println("--<Fun_Mediana: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Mediana, yycolumn, yyline, yytext());
            }
          // fall through
          case 100: break;
          case 47:
            { System.out.println("--<Program: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Program_Inicio, yycolumn, yyline, yytext());
            }
          // fall through
          case 101: break;
          case 48:
            { System.out.println("--<Titulo_X: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Titulo_X, yycolumn, yyline, yytext());
            }
          // fall through
          case 102: break;
          case 49:
            { System.out.println("--<Titulo_Y: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Titulo_Y, yycolumn, yyline, yytext());
            }
          // fall through
          case 103: break;
          case 50:
            { System.out.println("--<Grafica_Barras: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Barras, yycolumn, yyline, yytext());
            }
          // fall through
          case 104: break;
          case 51:
            { System.out.println("--<Grafica_Pie: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Pie, yycolumn, yyline, yytext());
            }
          // fall through
          case 105: break;
          case 52:
            { System.out.println("--<Fun_Varianza: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Varianza, yycolumn, yyline, yytext());
            }
          // fall through
          case 106: break;
          case 53:
            { System.out.println("--<Grafica_Lineal: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Lineal, yycolumn, yyline, yytext());
            }
          // fall through
          case 107: break;
          case 54:
            { System.out.println("--<Grafica_Histograma: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Histograma, yycolumn, yyline, yytext());
            }
          // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
