// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/DataForge/LexerCup.flex

package DataForge;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\2\2\1\1\22\0\1\3\1\0\1\4"+
    "\5\0\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\12\15\1\16\1\17\1\20\1\21\1\22\1\0"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\31\1\36\1\37\1\40\1\41"+
    "\1\42\1\31\1\43\1\44\1\45\1\46\1\47\1\31"+
    "\1\50\1\51\1\52\1\53\1\0\1\54\1\0\1\31"+
    "\1\0\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\31\1\36\1\37\1\40\1\41"+
    "\1\42\1\31\1\43\1\44\1\45\1\46\1\47\1\31"+
    "\1\50\1\51\1\52\12\0\1\2\252\0\2\55\115\0"+
    "\1\56\u01a8\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\1"+
    "\1\16\1\17\16\20\1\21\1\22\1\1\1\0\1\23"+
    "\1\0\1\24\1\0\1\25\1\26\5\20\1\0\5\20"+
    "\1\0\6\20\1\0\4\20\1\0\1\20\2\0\1\13"+
    "\1\27\3\20\1\30\1\20\1\30\1\20\1\31\3\20"+
    "\1\0\1\20\1\32\1\20\1\30\1\32\2\20\1\0"+
    "\1\20\1\0\1\20\1\33\3\20\1\0\1\20\1\34"+
    "\1\35\1\36\2\20\1\0\2\20\1\0\2\20\1\0"+
    "\1\20\1\0\2\20\2\0\2\20\1\0\3\20\1\0"+
    "\1\37\2\32\1\40\1\20\1\40\1\20\1\0\2\20"+
    "\1\0\1\41\1\42\1\20\1\0\1\41\4\20\1\0"+
    "\1\20\1\0\1\20\2\43\2\44\1\20\1\0\2\45"+
    "\2\20\1\0\1\20\1\0\1\20\1\0\1\46\1\47"+
    "\1\50\1\47\1\50\2\51\1\20\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\57\0\57\0\57\0\57"+
    "\0\57\0\274\0\57\0\57\0\353\0\u011a\0\57\0\u0149"+
    "\0\57\0\57\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263"+
    "\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db"+
    "\0\57\0\57\0\u040a\0\215\0\57\0\u0439\0\57\0\u0468"+
    "\0\57\0\57\0\u0497\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582"+
    "\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872"+
    "\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u0468\0\u01a7\0\u098c"+
    "\0\u09bb\0\u09ea\0\u01a7\0\u0a19\0\57\0\u0a48\0\u01a7\0\u0a77"+
    "\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u01a7\0\u0b62\0\u0b91\0\57"+
    "\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09"+
    "\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u01a7\0\u01a7\0\u01a7\0\u0df4"+
    "\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c"+
    "\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5\0\u10e4"+
    "\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u01a7\0\u11fe\0\u122d"+
    "\0\u01a7\0\u125c\0\57\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347"+
    "\0\57\0\u01a7\0\u1376\0\u13a5\0\u01a7\0\u13d4\0\u1403\0\u1432"+
    "\0\u1461\0\u1490\0\u0b91\0\u14bf\0\u14ee\0\u151d\0\u154c\0\u01a7"+
    "\0\57\0\u157b\0\u15aa\0\u01a7\0\57\0\u15d9\0\u1608\0\u1637"+
    "\0\u1666\0\u1695\0\u16c4\0\u16f3\0\u01a7\0\u01a7\0\u01a7\0\57"+
    "\0\57\0\u01a7\0\57\0\u1722\0\u1751";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\2\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\24\1\30\1\31\2\24\1\32\1\33\2\24"+
    "\1\34\1\35\1\36\1\37\1\24\1\40\3\24\1\41"+
    "\1\42\1\2\1\43\60\0\1\3\1\0\1\3\56\0"+
    "\1\44\1\45\5\0\1\44\2\0\1\46\1\44\5\0"+
    "\27\44\26\0\1\47\47\0\1\50\1\0\1\15\57\0"+
    "\1\51\52\0\1\52\61\0\1\24\6\0\17\24\1\53"+
    "\7\24\21\0\1\24\6\0\27\24\21\0\1\24\6\0"+
    "\7\24\1\54\5\24\1\55\11\24\21\0\1\24\6\0"+
    "\10\24\1\56\4\24\1\57\11\24\2\0\1\60\16\0"+
    "\1\24\6\0\11\24\1\61\2\24\1\62\7\24\1\63"+
    "\2\24\21\0\1\24\6\0\17\24\1\64\7\24\21\0"+
    "\1\24\6\0\10\24\1\65\16\24\2\0\1\66\16\0"+
    "\1\24\6\0\1\67\26\24\21\0\1\24\6\0\1\70"+
    "\3\24\1\71\3\24\1\72\4\24\1\73\4\24\1\74"+
    "\4\24\2\0\1\75\16\0\1\24\6\0\17\24\1\76"+
    "\7\24\21\0\1\24\6\0\4\24\1\77\22\24\21\0"+
    "\1\24\6\0\22\24\1\100\4\24\21\0\1\24\6\0"+
    "\10\24\1\101\16\24\2\0\1\102\16\0\1\24\6\0"+
    "\1\103\26\24\52\0\1\104\13\0\1\44\1\45\5\0"+
    "\1\44\1\105\1\0\1\46\1\44\5\0\27\44\21\0"+
    "\1\106\56\0\1\24\6\0\17\24\1\107\7\24\21\0"+
    "\1\24\6\0\1\110\26\24\21\0\1\24\6\0\12\24"+
    "\1\111\1\24\1\112\12\24\21\0\1\24\6\0\23\24"+
    "\1\113\3\24\21\0\1\24\6\0\22\24\1\114\4\24"+
    "\53\0\1\115\24\0\1\24\6\0\4\24\1\116\22\24"+
    "\21\0\1\24\6\0\3\24\1\117\23\24\21\0\1\24"+
    "\6\0\4\24\1\120\22\24\21\0\1\24\6\0\1\121"+
    "\26\24\21\0\1\24\6\0\20\24\1\122\6\24\3\0"+
    "\1\123\44\0\1\123\11\0\1\123\15\0\1\24\6\0"+
    "\1\24\1\124\25\24\21\0\1\24\6\0\24\24\1\125"+
    "\2\24\21\0\1\24\6\0\3\24\1\126\23\24\21\0"+
    "\1\24\6\0\14\24\1\125\12\24\21\0\1\24\6\0"+
    "\3\24\1\127\23\24\21\0\1\24\6\0\12\24\1\113"+
    "\14\24\44\0\1\130\33\0\1\24\6\0\10\24\1\131"+
    "\4\24\1\132\11\24\2\0\1\133\16\0\1\24\6\0"+
    "\20\24\1\113\6\24\3\0\1\115\15\0\1\24\6\0"+
    "\13\24\1\113\13\24\21\0\1\24\6\0\21\24\1\134"+
    "\5\24\51\0\1\135\26\0\1\24\6\0\12\24\1\136"+
    "\4\24\1\137\7\24\43\0\1\115\34\0\1\44\56\0"+
    "\1\24\6\0\17\24\1\140\7\24\21\0\1\24\6\0"+
    "\22\24\1\141\4\24\21\0\1\24\6\0\20\24\1\142"+
    "\6\24\3\0\1\143\15\0\1\24\6\0\1\24\1\144"+
    "\25\24\21\0\1\24\6\0\24\24\1\145\1\146\1\24"+
    "\21\0\1\24\6\0\2\24\1\147\24\24\21\0\1\24"+
    "\6\0\16\24\1\150\10\24\21\0\1\24\6\0\21\24"+
    "\1\151\5\24\51\0\1\152\26\0\1\24\6\0\4\24"+
    "\1\153\22\24\21\0\1\24\6\0\10\24\1\154\16\24"+
    "\2\0\1\155\16\0\1\24\6\0\1\125\26\24\21\0"+
    "\1\24\6\0\14\24\1\156\12\24\21\0\1\24\6\0"+
    "\6\24\1\157\20\24\44\0\1\160\33\0\1\24\6\0"+
    "\22\24\1\161\4\24\52\0\1\162\25\0\1\24\6\0"+
    "\22\24\1\163\4\24\21\0\1\24\6\0\10\24\1\164"+
    "\16\24\2\0\1\165\16\0\1\24\6\0\27\24\1\166"+
    "\20\0\1\24\6\0\13\24\1\167\13\24\21\0\1\24"+
    "\6\0\15\24\1\170\11\24\45\0\1\171\32\0\1\24"+
    "\6\0\12\24\1\172\14\24\21\0\1\24\6\0\7\24"+
    "\1\173\17\24\21\0\1\24\6\0\15\24\1\174\11\24"+
    "\45\0\1\175\32\0\1\24\6\0\12\24\1\176\14\24"+
    "\21\0\1\24\6\0\1\177\26\24\30\0\1\200\47\0"+
    "\1\24\6\0\21\24\1\201\5\24\21\0\1\24\6\0"+
    "\17\24\1\202\7\24\51\0\1\203\26\0\1\24\6\0"+
    "\12\24\1\204\14\24\42\0\1\205\35\0\1\24\6\0"+
    "\4\24\1\206\22\24\21\0\1\24\6\0\1\207\26\24"+
    "\30\0\1\210\106\0\1\211\17\0\1\24\6\0\14\24"+
    "\1\212\12\24\21\0\1\24\6\0\12\24\1\213\14\24"+
    "\42\0\1\214\35\0\1\24\6\0\4\24\1\215\22\24"+
    "\21\0\1\24\6\0\1\24\1\216\10\24\1\217\3\24"+
    "\1\220\10\24\21\0\1\24\6\0\6\24\1\221\20\24"+
    "\36\0\1\222\41\0\1\24\6\0\14\24\1\223\12\24"+
    "\44\0\1\224\33\0\1\24\6\0\1\225\26\24\21\0"+
    "\1\24\6\0\15\24\1\226\11\24\45\0\1\227\32\0"+
    "\1\24\6\0\20\24\1\230\6\24\3\0\1\231\15\0"+
    "\1\24\6\0\14\24\1\232\12\24\44\0\1\233\33\0"+
    "\1\24\6\0\4\24\1\234\22\24\34\0\1\235\43\0"+
    "\1\24\6\0\1\236\26\24\21\0\1\24\6\0\10\24"+
    "\1\237\16\24\2\0\1\240\16\0\1\24\6\0\10\24"+
    "\1\241\16\24\2\0\1\242\16\0\1\24\6\0\17\24"+
    "\1\243\7\24\47\0\1\244\37\0\1\130\47\0\1\24"+
    "\6\0\13\24\1\245\13\24\21\0\1\24\6\0\24\24"+
    "\1\246\1\247\1\24\54\0\1\250\1\251\22\0\1\24"+
    "\6\0\26\24\1\223\56\0\1\224\21\0\1\24\6\0"+
    "\17\24\1\252\7\24\21\0\1\24\6\0\14\24\1\241"+
    "\12\24\44\0\1\242\33\0\1\24\6\0\4\24\1\252"+
    "\22\24\34\0\1\253\43\0\1\24\6\0\1\254\26\24"+
    "\30\0\1\255\47\0\1\24\6\0\13\24\1\252\13\24"+
    "\43\0\1\253\17\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6016];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\5\11\1\1\2\11\2\1\1\11"+
    "\1\1\2\11\16\1\2\11\1\1\1\0\1\11\1\0"+
    "\1\11\1\0\2\11\5\1\1\0\5\1\1\0\6\1"+
    "\1\0\4\1\1\0\1\1\2\0\7\1\1\11\5\1"+
    "\1\0\4\1\1\11\2\1\1\0\1\1\1\0\5\1"+
    "\1\0\6\1\1\0\2\1\1\0\2\1\1\0\1\1"+
    "\1\0\2\1\2\0\2\1\1\0\3\1\1\0\5\1"+
    "\1\11\1\1\1\0\2\1\1\0\1\11\2\1\1\0"+
    "\5\1\1\0\1\1\1\0\4\1\1\11\1\1\1\0"+
    "\1\1\1\11\2\1\1\0\1\1\1\0\1\1\1\0"+
    "\3\1\2\11\1\1\1\11\1\1\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCup(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(sym.ERROR, yycolumn, yyline, yytext());
            }
          // fall through
          case 42: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 43: break;
          case 3:
            { System.out.println("--<Parentesis_Izq: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Parentesis_Izq, yycolumn, yyline, yytext());
            }
          // fall through
          case 44: break;
          case 4:
            { System.out.println("--<Parentesis_Der: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Parentesis_Der, yycolumn, yyline, yytext());
            }
          // fall through
          case 45: break;
          case 5:
            { System.out.println("--<Signo_Multiplicacion: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Multiplicacion, yycolumn, yyline, yytext());
            }
          // fall through
          case 46: break;
          case 6:
            { System.out.println("--<Signo_Suma: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Suma, yycolumn, yyline, yytext());
            }
          // fall through
          case 47: break;
          case 7:
            { System.out.println("--<Coma: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Coma, yycolumn, yyline, yytext());
            }
          // fall through
          case 48: break;
          case 8:
            { System.out.println("--<Signo_Resta: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Resta, yycolumn, yyline, yytext());
            }
          // fall through
          case 49: break;
          case 9:
            { System.out.println("--<Punto: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Punto, yycolumn, yyline, yytext());
            }
          // fall through
          case 50: break;
          case 10:
            { System.out.println("--<Signo_Division: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Division, yycolumn, yyline, yytext());
            }
          // fall through
          case 51: break;
          case 11:
            { System.out.println("--<Numero: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Numero, yycolumn, yyline, yytext());
            }
          // fall through
          case 52: break;
          case 12:
            { System.out.println("--<Dos_Puntos: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Dos_Puntos, yycolumn, yyline, yytext());
            }
          // fall through
          case 53: break;
          case 13:
            { System.out.println("--<Punto_Coma: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Punto_Coma, yycolumn, yyline, yytext());
            }
          // fall through
          case 54: break;
          case 14:
            { System.out.println("--<Signo_Igual: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Igual, yycolumn, yyline, yytext());
            }
          // fall through
          case 55: break;
          case 15:
            { System.out.println("--<Signo_Arroba: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Arroba, yycolumn, yyline, yytext());
            }
          // fall through
          case 56: break;
          case 16:
            { System.out.println("--<Identificador: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Identificador, yycolumn, yyline, yytext());
            }
          // fall through
          case 57: break;
          case 17:
            { System.out.println("--<Corchete_Izq: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Corchete_Izq, yycolumn, yyline, yytext());
            }
          // fall through
          case 58: break;
          case 18:
            { System.out.println("--<Corchete_Der: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Corchete_Der, yycolumn, yyline, yytext());
            }
          // fall through
          case 59: break;
          case 19:
            { System.out.println("--<Char_General: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Char_General, yycolumn, yyline, yytext());
            }
          // fall through
          case 60: break;
          case 20:
            { System.out.println("--<Signo_IndicadorR: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_IndicadorR, yycolumn, yyline, yytext());
            }
          // fall through
          case 61: break;
          case 21:
            { System.out.println("--<DosPuntos_Dobles: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.DosPuntos_Dobles, yycolumn, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 22:
            { System.out.println("--<Signo_Indicador: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Signo_Indicador, yycolumn, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 23:
            { System.out.println("--<Array: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Array, yycolumn, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 24:
            { System.out.println("--<Fun_Arit: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Arit, yycolumn, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 25:
            { System.out.println("--<End: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.End, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 26:
            { System.out.println("--<Fun_Esta: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Esta, yycolumn, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 27:
            { System.out.println("--<Variable: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Variable, yycolumn, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 28:
            { System.out.println("--<Eje_X: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Eje_X, yycolumn, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 29:
            { System.out.println("--<Eje_Y: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Eje_Y, yycolumn, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 30:
            { System.out.println("--<Ejecutar: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Ejecutar, yycolumn, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 31:
            { System.out.println("--<Grafica_Label: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Label, yycolumn, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 32:
            { System.out.println("--<Imprimir: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Imprimir, yycolumn, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 33:
            { System.out.println("--<Var_Tipo: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Var_Tipo, yycolumn, yyline, yytext());
            }
          // fall through
          case 74: break;
          case 34:
            { System.out.println("--<Columna: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Columna, yycolumn, yyline, yytext());
            }
          // fall through
          case 75: break;
          case 35:
            { System.out.println("--<Titulo: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Titulo, yycolumn, yyline, yytext());
            }
          // fall through
          case 76: break;
          case 36:
            { System.out.println("--<Grafica_Valores: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Grafica_Valores, yycolumn, yyline, yytext());
            }
          // fall through
          case 77: break;
          case 37:
            { System.out.println("--<Fun_Consola: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Fun_Consola, yycolumn, yyline, yytext());
            }
          // fall through
          case 78: break;
          case 38:
            { System.out.println("--<Program: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Program, yycolumn, yyline, yytext());
            }
          // fall through
          case 79: break;
          case 39:
            { System.out.println("--<Titulo_X: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Titulo_X, yycolumn, yyline, yytext());
            }
          // fall through
          case 80: break;
          case 40:
            { System.out.println("--<Titulo_Y: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Titulo_Y, yycolumn, yyline, yytext());
            }
          // fall through
          case 81: break;
          case 41:
            { System.out.println("--<Tipo_Grafica: " +yytext() + " || linea: "+ yyline + " ||columna: "+ yycolumn+">");return new Symbol(sym.Tipo_Grafica, yycolumn, yyline, yytext());
            }
          // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
