
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package DataForge;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Eje_X = 25;
  public static final int Parentesis_Der = 9;
  public static final int Corchete_Der = 11;
  public static final int Signo_Arroba = 37;
  public static final int Coma = 35;
  public static final int End = 13;
  public static final int Grafica_Label = 29;
  public static final int DosPuntos_Dobles = 31;
  public static final int Dos_Puntos = 33;
  public static final int Variable = 14;
  public static final int Titulo_Y = 28;
  public static final int Titulo_X = 27;
  public static final int Titulo = 24;
  public static final int Signo_IndicadorR = 43;
  public static final int Char_General = 40;
  public static final int Punto = 34;
  public static final int Columna = 21;
  public static final int Var_Tipo = 15;
  public static final int Ejecutar = 22;
  public static final int EOF = 0;
  public static final int Signo_Suma = 4;
  public static final int COMILLA = 41;
  public static final int error = 1;
  public static final int Fun_Arit = 17;
  public static final int Linea = 2;
  public static final int Parentesis_Izq = 8;
  public static final int Corchete_Izq = 10;
  public static final int Imprimir = 20;
  public static final int Fun_Consola = 19;
  public static final int Grafica_Valores = 30;
  public static final int Signo_Division = 7;
  public static final int ERROR = 39;
  public static final int Fun_Esta = 18;
  public static final int Signo_Resta = 5;
  public static final int Punto_Coma = 32;
  public static final int Identificador = 38;
  public static final int Signo_Igual = 3;
  public static final int Signo_Multiplicacion = 6;
  public static final int Array = 16;
  public static final int Signo_Indicador = 36;
  public static final int Numero = 42;
  public static final int Program = 12;
  public static final int Tipo_Grafica = 23;
  public static final int Eje_Y = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "Signo_Igual",
  "Signo_Suma",
  "Signo_Resta",
  "Signo_Multiplicacion",
  "Signo_Division",
  "Parentesis_Izq",
  "Parentesis_Der",
  "Corchete_Izq",
  "Corchete_Der",
  "Program",
  "End",
  "Variable",
  "Var_Tipo",
  "Array",
  "Fun_Arit",
  "Fun_Esta",
  "Fun_Consola",
  "Imprimir",
  "Columna",
  "Ejecutar",
  "Tipo_Grafica",
  "Titulo",
  "Eje_X",
  "Eje_Y",
  "Titulo_X",
  "Titulo_Y",
  "Grafica_Label",
  "Grafica_Valores",
  "DosPuntos_Dobles",
  "Punto_Coma",
  "Dos_Puntos",
  "Punto",
  "Coma",
  "Signo_Indicador",
  "Signo_Arroba",
  "Identificador",
  "ERROR",
  "Char_General",
  "COMILLA",
  "Numero",
  "Signo_IndicadorR"
  };
}

